import Head from "next/head";
import { useState } from "react";
import Layout from "../../components/Layout/Layout.js";
import Rooms from "../../components/Rooms/Rooms.js";

export default function RoomsPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Syncro Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <button
            onClick={() => {
              setIsModalOpen(true);
            }}
          >
            Create room
          </button>

          <Rooms />
        </main>
      </Layout>
    </>
  );
}
