import Head from "next/head";
import { useState } from "react";
import CreateRoomForm from "../../components/CreateRoomForm/CreateRoomForm.js";
import Layout from "../../components/Layout/Layout.js";

export default function Rooms() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Syncro Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <button
            onClick={() => {
              setIsModalOpen(true);
            }}
          >
            Create room
          </button>
          {isModalOpen ? (
            <>
              <CreateRoomForm />
            </>
          ) : (
            <></>
          )}
        </main>
      </Layout>
    </>
  );
}
